#!/bin/bash

source_dir="$1"
matching_dir_pattern="$2"
latest_destination_dir="$3"
slack_channel=${4:-data}
seconds=${5:-5}
dimesnion_storage=${6:-"/Users/matthew.newland/Resilio Sync/dimension"}
secret="${dimesnion_storage}/.slack.${slack_channel}"

[ ! -d "${latest_destination_dir}" ] && mkdir "${latest_destination_dir}"

echo "========================= Start [$(date)] ================================="
echo "Source: [${source_dir}]"
echo "Matching: [${matching_dir_pattern}]"
echo "Latest: [${latest_destination_dir}]"
echo "Waiting for ${seconds} seconds"

sleep "${seconds}"
echo Updating latest
# Copy the any newer files in the $latest_dir in $source_dir to the $latest_destination_dir
find_newest_cmd=("/usr/local/bin/gfind" "${source_dir}" -maxdepth 1 -mindepth 1 -type d -name "${matching_dir_pattern}" )
latest_dir="$("${find_newest_cmd[@]}" | sort | tail -1)"
echo "From ${latest_dir}"
data_id="id.${latest_dir##*/*_}"
if [[ ! -f "${latest_destination_dir}"/"${data_id}" ]]; then
  echo "Wiping and setting latest id to ${data_id}"
  rm -f  "${latest_destination_dir}"/*
  touch ${latest_destination_dir}/${data_id}
  if [[ -f "$secret" ]]; then
    slack_url="$(cat "$secret")"
    data='{"text":"New Data Set Landed '${data_id}\"'}'
    echo Sending slack message "$data" to channel ${slack_channel}
    curl -X POST -H 'Content-type: application/json' --data "${data}" "${slack_url}"
  fi
else
  echo "Found latest id ${data_id}"
fi
rsync -a -c --verbose "${latest_dir}"/* "${latest_destination_dir}"
echo "========================= End [$(date)] ================================="
